### ISSUE TITLE
Information displayed incorrectly

### ISSUE THREAD

**Issue by mamadou-diallo** [NathanPang001/PYLinkChecker#1]
![image](https://user-images.githubusercontent.com/25627082/94628379-d4470300-028d-11eb-802a-25458becf855.png)

When reading content from an HTML page, the program reads ALL the information about the page and produces information that shouldn't be displayed like HTML tags & regular text.
Code should be updated to ONLY display html links.

**Comment by NathanPang001** [comment]
Fixed
