### ISSUE TITLE
Feature: Ignore URL Patterns

### ISSUE THREAD

**Issue by NesaByte** [NathanPang001/PYLinkChecker#13]
Hey Nathan, there's this feature from Professor Humpd:

"Users want to be able to run our link checker tools and be able to include an extra argument, a file of URL patterns to be ignored"

I'm wondering if you want this feature in your project, if you do I'd love to work on your project. Thank you.

**Comment by NathanPang001** [comment]
Sure! That sounds great, I would love for you to add that feature to the project.

**Comment by NesaByte** [comment]
Thank you 🙏🏻 will update you soon!

**Comment by NesaByte** [comment]
Hey Nathan, I have problems with running the project. I tried piping it, but it wouldnt let me so I git cloned it from github and did: python setup.py install. Still not running tho, I have no idea what's the problem but this is what I got: 

![](https://cdn.discordapp.com/attachments/755989430518546564/767300382887772170/unknown.png)

Do you mind guiding me through this? Maybe in discord, if u have? 
Sorry and Thank you so much!

**Comment by NesaByte** [comment]
I got it to magically work, no worries now. I sent you a Pull Request. Thank you.

**Comment by NathanPang001** [comment]
Sorry I couldn't help you with the urllib3 PoolManager, glad you got through it though. Thank you for working on this project and helping me make it better! I will close this issue and accept the pull request after I finish testing.
