### ISSUE TITLE
Invalid Error Messages

### ISSUE THREAD

**Issue by mamadou-diallo** [NathanPang001/PYLinkChecker#2]
![image](https://user-images.githubusercontent.com/25627082/94630405-a82e8080-0293-11eb-89a1-84e52c9be92d.png)

Results that are do not give the code "200", "403" or "404" should return the message that it is Unknown.
As seen in the picture attached, the code would only return if the it is a valid link or not.

**Comment by NathanPang001** [comment]
Fixed
